package com.example.financeapp

// org.jetbrains.annotations.NotNull is not needed explicitly in Kotlin for return types
// as non-null is the default. For parameters, it's also default non-null.

data class Transaction(
    var id: Long, // 'var' because there's a setId method, implying it can change.
                 // If it's only set at construction or by DB, it could be 'val'
                 // and setId removed or handled differently.
                 // For now, matching existing mutability.
    val amount: Double, // 'val' because it's final in Java and no setter.
    val note: String,   // 'val' for the same reason.
    var timestamp: String? // 'var' because there's a setter. Made nullable String?
                           // as timestamps can sometimes be missing or null from DB before set.
                           // The Java version implies it can be null by not being final and having a setter.
) {
    // The toString() method is automatically generated by data classes
    // in a standard format like "Transaction(id=1, amount=100.0, note=Salary, timestamp=...)"
    // If the specific "Rp. " format is crucial, we need to override it.
    override fun toString(): String {
        return "Rp. $amount - $note"
    }
}
